In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

In [3]:
data_1401 = pd.read_excel("1401.xlsx",header=[0,1])
data_1402 = pd.read_excel("1402.xlsx",header=[0,1])
data_1403 = pd.read_excel("1403.xlsx",header=[0,1])

In [4]:
data_1401.columns

MultiIndex([(      'نام مشترک',  'Unnamed: 0_level_1'),
            (      'کد اشتراک',  'Unnamed: 1_level_1'),
            (     'نوع پروانه',  'Unnamed: 2_level_1'),
            (          'استان',  'Unnamed: 3_level_1'),
            (        'شهرستان',  'Unnamed: 4_level_1'),
            (        'امور آب',  'Unnamed: 5_level_1'),
            ('محدوده مطالعاتی',  'Unnamed: 6_level_1'),
            (    'سریال کنتور',  'Unnamed: 7_level_1'),
            (     'سایز کنتور',  'Unnamed: 8_level_1'),
            (      'تاریخ نصب',  'Unnamed: 9_level_1'),
            ...
            (        '1401/11',   'تعداد مورد انتظار'),
            (        '1401/11',  'درصد اطلاعات موجود'),
            (        '1401/12',             'دبی l/s'),
            (        '1401/12',      'تعداد دبی منفی'),
            (        '1401/12',       'درصد دبی منفی'),
            (        '1401/12',     'ساعت کارکرد (h)'),
            (        '1401/12',      'مصرف (m³) (m³)'),
            (        '1401/12', 'تعداد اطلاعات موجود'),
            (        '1401/12',   'تعداد مورد انتظار'),
            (        '1401/12',  'درصد اطلاعات موجود')],
           length=111)

In [5]:
data_1401.head()

                   نام مشترک          کد اشتراک         نوع پروانه  \
          Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
0                  آرمند بتن             520009              صنعتی
1   ابوالفضل  خورسند اترآباد             200654            کشاورزی
2        ابوالفضل  مقرب زاده             622162            کشاورزی
3        احمد  ابراهیمی مقدم             515618            کشاورزی
4      احمد  جوپای ناجی آباد             529232            کشاورزی

               استان            شهرستان            امور آب    محدوده مطالعاتی  \
  Unnamed: 3_level_1 Unnamed: 4_level_1 Unnamed: 5_level_1 Unnamed: 6_level_1
0        خراسان رضوی               مشهد                NaN                NaN
1        خراسان رضوی              قوچان                NaN                NaN
2        خراسان رضوی        تربت حیدریه                NaN                NaN
3        خراسان رضوی               مشهد                NaN                NaN
4        خراسان رضوی               مشهد                NaN                NaN

         سریال کنتور         سایز کنتور          تاریخ نصب  ...  \
  Unnamed: 7_level_1 Unnamed: 8_level_1 Unnamed: 9_level_1  ...
0       909801058196                 50         1402/11/15  ...
1       909801034787                 80         1400/02/12  ...
2       909801061701                 50         1403/02/27  ...
3       909801035022                125         1400/02/30  ...
4       909801046032                125         1401/06/23  ...

            1401/11                    1401/12                               \
  تعداد مورد انتظار درصد اطلاعات موجود دبی l/s تعداد دبی منفی درصد دبی منفی
0                30                0.0     NaN              0             0
1                30              100.0    1.06              0             0
2                30                0.0     NaN              0             0
3                30                0.0     NaN              0             0
4                30              100.0    5.78              0             0

                                                                        \
  ساعت کارکرد (h) مصرف (m³) (m³) تعداد اطلاعات موجود تعداد مورد انتظار
0             NaN            NaN                   0                29
1         17190.7         638.81                  29                29
2             NaN            NaN                   0                29
3             NaN            NaN                   0                29
4         26865.2       14161.93                  29                29


  درصد اطلاعات موجود
0                0.0
1              100.0
2                0.0
3                0.0
4              100.0

[5 rows x 111 columns]

In [6]:
data_1401.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2218 entries, 0 to 2217
Columns: 111 entries, ('نام مشترک', 'Unnamed: 0_level_1') to ('1401/12', 'درصد اطلاعات موجود')
dtypes: bool(1), float64(59), int64(43), object(8)
memory usage: 1.9+ MB

In [7]:
data_1401 = data_1401.iloc[1:][:]

In [8]:
data_1401.iloc[0]

Unnamed: 0_level_1      ابوالفضل  خورسند اترآباد
Unnamed: 1_level_1                        200654
Unnamed: 2_level_1                       کشاورزی
Unnamed: 3_level_1                   خراسان رضوی
Unnamed: 4_level_1                         قوچان
                                 ...
ساعت کارکرد (h)                          17190.7
مصرف (m³) (m³)                            638.81
تعداد اطلاعات موجود                           29
تعداد مورد انتظار                             29
درصد اطلاعات موجود                         100.0
Name: 1, Length: 111, dtype: object

In [9]:
data_1401.columns

Index(['Unnamed: 0_level_1', 'Unnamed: 1_level_1', 'Unnamed: 2_level_1',
       'Unnamed: 3_level_1', 'Unnamed: 4_level_1', 'Unnamed: 5_level_1',
       'Unnamed: 6_level_1', 'Unnamed: 7_level_1', 'Unnamed: 8_level_1',
       'Unnamed: 9_level_1',
       ...
       'تعداد مورد انتظار', 'درصد اطلاعات موجود', 'دبی l/s', 'تعداد دبی منفی',
       'درصد دبی منفی', 'ساعت کارکرد (h)', 'مصرف (m³) (m³)',
       'تعداد اطلاعات موجود', 'تعداد مورد انتظار', 'درصد اطلاعات موجود'],
      dtype='object', length=111)

In [10]:
data_1402.columns

MultiIndex([(      'نام مشترک',  'Unnamed: 0_level_1'),
            (      'کد اشتراک',  'Unnamed: 1_level_1'),
            (     'نوع پروانه',  'Unnamed: 2_level_1'),
            (          'استان',  'Unnamed: 3_level_1'),
            (        'شهرستان',  'Unnamed: 4_level_1'),
            (        'امور آب',  'Unnamed: 5_level_1'),
            ('محدوده مطالعاتی',  'Unnamed: 6_level_1'),
            (    'سریال کنتور',  'Unnamed: 7_level_1'),
            (     'سایز کنتور',  'Unnamed: 8_level_1'),
            (      'تاریخ نصب',  'Unnamed: 9_level_1'),
            ...
            (        '1402/11',   'تعداد مورد انتظار'),
            (        '1402/11',  'درصد اطلاعات موجود'),
            (        '1402/12',             'دبی l/s'),
            (        '1402/12',      'تعداد دبی منفی'),
            (        '1402/12',       'درصد دبی منفی'),
            (        '1402/12',     'ساعت کارکرد (h)'),
            (        '1402/12',      'مصرف (m³) (m³)'),
            (        '1402/12', 'تعداد اطلاعات موجود'),
            (        '1402/12',   'تعداد مورد انتظار'),
            (        '1402/12',  'درصد اطلاعات موجود')],
           length=111)

In [11]:
cols = [data_1401.columns[i] for i in range(len(data_1401.columns)) if data_1401.columns[i][0] != "U" and data_1401.columns[i][0] != "1"]

In [12]:
len(cols)

96

In [13]:
type(cols[0])

str

In [14]:
cols

['دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود',
 'دبی l/s',
 'تعداد دبی منفی',
 'درصد دبی منفی',
 'ساعت کارکرد (h)',
 'مصرف (m³) (m³)',
 'تعداد اطلاعات موجود',
 'تعداد مورد انتظار',
 'درصد اطلاعات موجود']

In [15]:
usage_1401 = data_1401.iloc[:][14:]

In [16]:
usage_1401.head()

,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Unnamed: 5_level_1,Unnamed: 6_level_1,Unnamed: 7_level_1,Unnamed: 8_level_1,Unnamed: 9_level_1,...,تعداد مورد انتظار,درصد اطلاعات موجود,دبی l/s,تعداد دبی منفی,درصد دبی منفی,ساعت کارکرد (h),مصرف (m³) (m³),تعداد اطلاعات موجود,تعداد مورد انتظار,درصد اطلاعات موجود
15,تعاونی مرغداری آزادگان,608033,شرب و بهداشت دام,خراسان رضوی,کاشمر,NaN,NaN,909801052337,50,1402/07/09,...,30,0.00,NaN,0,0,NaN,NaN,0,29,0.0
16,تولیدی کشاورزی دامداری رضایت جام,911593,شرب و بهداشت دام,خراسان رضوی,تربت جام,NaN,NaN,909801036862,50,1400/08/04,...,30,100.00,0.50,0,0,680.6,1225.03,29,29,100.0
17,جلیل کریم زاده صابونی,529338,کشاورزی,خراسان رضوی,مشهد,NaN,NaN,909801035351,150,1400/03/30,...,30,46.67,15.67,0,0,25076.4,38057.80,29,29,100.0
18,حجت حسن پور,519787,کشاورزی,خراسان رضوی,مشهد,NaN,NaN,909801034846,125,1400/03/24,...,30,40.00,13.27,0,0,34480.5,17211.90,29,29,100.0
19,حسن صادقیان,302105,کشاورزی,خراسان رضوی,گناباد,NaN,NaN,909801033223,100,1399/08/11,...,30,100.00,1.60,0,0,2828.0,40.72,29,29,100.0

In [17]:
1238/len(data_1401)

0.5584122688317547

In [ ]:
data_1401.describe()

In [24]:
display(data_1401.isna().sum())

Unnamed: 0_level_1        0
Unnamed: 1_level_1        0
Unnamed: 2_level_1      651
Unnamed: 3_level_1        0
Unnamed: 4_level_1        0
Unnamed: 5_level_1     2216
Unnamed: 6_level_1     2217
Unnamed: 7_level_1        0
Unnamed: 8_level_1        0
Unnamed: 9_level_1        0
Unnamed: 10_level_1     106
Unnamed: 11_level_1       0
Unnamed: 12_level_1     898
Unnamed: 13_level_1    1017
Unnamed: 14_level_1    1036
دبی l/s                1469
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1369
مصرف (m³) (m³)         1243
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1422
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1323
مصرف (m³) (m³)         1199
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1397
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1300
مصرف (m³) (m³)         1196
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1379
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1306
مصرف (m³) (m³)         1186
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1375
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1369
مصرف (m³) (m³)         1189
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1368
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1365
مصرف (m³) (m³)         1175
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1384
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1368
مصرف (m³) (m³)         1159
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1393
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1394
مصرف (m³) (m³)         1141
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1387
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1410
مصرف (m³) (m³)         1115
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1425
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1443
مصرف (m³) (m³)         1101
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1480
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1500
مصرف (m³) (m³)         1087
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
دبی l/s                1396
تعداد دبی منفی            0
درصد دبی منفی             0
ساعت کارکرد (h)        1342
مصرف (m³) (m³)         1088
تعداد اطلاعات موجود       0
تعداد مورد انتظار         0
درصد اطلاعات موجود        0
dtype: int64

In [25]:
2216 / len(data_1401)

0.9995489400090212